<?php
    define('RESTAPIServer',"http://10.165.168.14/rest");
    define('vmmServer',"EISILVMM.EISLAB-IL.INTRA");
    $JobsDbServer="10.165.168.15";
    $JobsDbUser="root";
    $JobsDbPassword="ESXpumpkin1";
    $JobsDbDatabase="vmmui";
    define('CacheDbServer',"10.165.168.15");
    define('CacheDbUser',"root");
    define('CacheDbPassword',"ESXpumpkin1");
    define('CacheDbDatabase',"cache");
